### ISSUE TITLE
typo of autos-save extension

### ISSUE THREAD

**Issue by wpchou** [manateelazycat/lazycat-emacs#13]
https://github.com/manateelazycat/lazycat-emacs/blob/master/site-lisp/extensions/lazycat/auto-save.el#L99

It's silent, not slient

**Comment by ziqiangxu** [comment]
They are the same

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/commit/5ce5ff4237bc7bfb21c3677ae75e01d9139f7c22 has fixed, thanks for report!
