### ISSUE TITLE
auto-save.el 报错 Error running timer ‘auto-save-buffers’: (user-error "Unmatched bracket or quote")

### ISSUE THREAD

**Issue by samrayleung** [manateelazycat/lazycat-emacs#16]
Hi 老王，咨询个关于`auto-save.el`插件的问题，我用`auto-save.el` 这个插件应该也有两三年了，但是一直会遇到一个问题, 出现频率倒不高, 详细信息如下: 
#### 报错信息:
```
Error running timer ‘auto-save-buffers’: (user-error "Unmatched bracket or quote")
```
#### 尝试自行解决步骤
1. 尝试开启` toggle-debug-on-error`调试无果，没有错误堆栈.
2. google 搜索相关错误无果

### 复现步骤:
1. 新增`test.md`文件
2. 输入以下信息:
```
1 －》 
```
3. *Message* 显露错误信息

调试之后还是无法解决问题，只能来请教您这位作者了呢 :）

**Comment by manateelazycat** [comment]
我这边用你的重现步骤测试了, 没有问题.

我的建议, 我估计是你保存的时候, 有什么插件在检查括号匹配的问题, 请使用 Emacs -Q 只加载 auto-save.el 插件去排查问题.

我确定这个错误不是 auto-save.el 引起的.

如果你确定是 auto-save.el 引起的, 请重新打开issue.
