### ISSUE TITLE
ubuntu下安装出现 Font not available

### ISSUE THREAD

**Issue by eiuapp** [manateelazycat/lazycat-emacs#17]
## 环境
os: ubuntu16
emacs: 26.1 

Droid Sans Mono 字体有通过以下命令安装

```bash
sudo apt-get install fonts-droid-fallback
```

## 操作

经过了下载emacs的源码，并编译安装 emacs 后，启动。

emacs 

## 效果

然后出现如下错误

```bash
Eager macro-expansion failure: (void-function -map)
set-face-attribute: Font not available: #<font-spec nil nil Droid\ Sans\ Mono-14 nil nil nil nil nil nil nil nil nil ((:name . "Droid Sans Mono-14") (:user-spec . "Droid Sans Mono-14"))>
```

是否字体安装或配置错误？

## 其它

另问，有没有ubuntu下安装指北？

**Comment by manateelazycat** [comment]
参考这个地方： https://github.com/manateelazycat/lazycat-theme/blob/6d59ca1e01d450beae6603dd786f8e7bd4087826/lazycat-theme.el#L10
