### ISSUE TITLE
Please use additional repositories

### ISSUE THREAD

**Issue by tarsius** [manateelazycat/lazycat-emacs#19]
Please consider using a separate dedicated repository for each of your own packages. This is more convenient for people who want to use only one of your packages and would like to get it by cloning its repository. Some people, including myself, prefer installing from a git repository over using `package.el` for a variety of reasons.

This repository already contains some packages in the form of git submodules so it seems you know how to deal with the sharp edges of that approach. Please consider doing the same with your own packages.

You might also look at my [`borg`](https://github.com/emacscollective/borg) package manager. In the [announcement](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/) I also described some benefits of using git modules for package installation.

**Comment by manateelazycat** [comment]
I have developed hundreds of plugins, many of which are very small, so I didn't stand out.
I will handle multi-term.el on weekends.

**Comment by tarsius** [comment]
Could you also do that for your other packages that are available from Melpa? (`chm-view`, `dired-sort` and `irfc`)

**Comment by tarsius** [comment]
According to the readme file all your extensions are under `site-lisp/extensions`, but it appears that all the plugins that you yourself have written are actually under `site-lisp/extensions/lazycat`. Is that correct?

**Comment by manateelazycat** [comment]
> Could you also do that for your other packages that are available from Melpa? (`chm-view`, `dired-sort` and `irfc`)

No，I don't like Melpa.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/multi-term is created.

**Comment by tarsius** [comment]
Thanks!
