### ISSUE TITLE
如何切换tab窗口

### ISSUE THREAD

**Issue by eiuapp** [manateelazycat/lazycat-emacs#21]
## 现象

buffer 总数是

![](https://raw.githubusercontent.com/eiuapp/img/master/img/20190724103755.png)

窗口A的buffer是

![](https://raw.githubusercontent.com/eiuapp/img/master/img/20190724103905.png)

另一个窗口B打开只有 a.el 文件

![](https://raw.githubusercontent.com/eiuapp/img/master/img/20190724102915.png?token=AJOUPLZQLLW2KL75ATYKAEK5G7BLW)

在 窗口A下，可通过 alt-7, alt-8 来回切换，但是，切换不到 a.el buffer

## 问题 

@manateelazycat 请教：

1. 如何从 当前 a.el buffer 窗口，切换至 *message* buffer？
2. 之间的逻辑关系，在哪里查看或理解？

**Comment by manateelazycat** [comment]
alt+9 和 alt + 0可以切换组
