### ISSUE TITLE
贴子“十年没按保存键”中auto-save.el链接挂了

### ISSUE THREAD

**Issue by yundeep** [manateelazycat/lazycat-emacs#22]
您好，如题，文章中auto-save.el下载不了了。
还有，源码解析中，第二段中“; 第一个参数...”那-save写拼成s-ave了。
最后感谢文章及相关文章中细致耐心的讲解(我是一个英语渣),期待您的基础文章的续集

**Comment by manateelazycat** [comment]
独立成github仓库了，我一会改一下文章中的链接

谢谢指出问题
