### ISSUE TITLE
Mac 下 .emacs 无效

### ISSUE THREAD

**Issue by nehcuh** [manateelazycat/lazycat-emacs#24]
RT，按照 REAMDE 进行 emacs 编译，下载配置文件，并且设置了 .emacs
但是实际 emacs 没有使用 .emacs 的配置文件
另外，补充一下，为了在终端下使用 emacs，最好设置一下 alias, 不然打开的是 mac 自带的 emacs

**Comment by manateelazycat** [comment]
请确保 .emacs 下的 dd-subdirs-to-load-path 路径是正确的路径。

BTW，这个只是个人项目，建议你借鉴里面的配置，这个不是Emacs发行版，不会就这个项目遇到的问题进行修复和调整。

感谢你的反馈
