### ISSUE TITLE
无法在Mac OS下配置

### ISSUE THREAD

**Issue by yibie** [manateelazycat/lazycat-emacs#29]
在终端输入：
>git clone --depth 1 git://git.savannah.gnu.org/emacs.git 

报错：
>正克隆到 'emacs'...
>fatal: 无法读取远程仓库。

**Comment by Eason0210** [comment]
这个仓库下载比较慢，你如果想用最新版的Emacs28.0.50 可以下载Github的镜像。
`git clone https://github.com/emacs-mirror/emacs.git`
