### ISSUE TITLE
extension find-orphan branch name issue

### ISSUE THREAD

**Issue by drcxd** [manateelazycat/lazycat-emacs#35]
I was trying to install your emacs configuration and when excuting `git submodule foreach git checkout master` I got the following error:
```
Entering 'site-lisp/extensions/find-orphan'
error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for site-lisp/extensions/find-orphan
.
```
I checked the find-orphan repository and found that there was only one `main` branch. Should that be renamed to `master`?

This also happens to `grammatical-edit`, `isearch-mb`, `one-key` and maybe some more extensions.

**Comment by manateelazycat** [comment]
Sure, just switch to main.

Note this is repo for self usage, just copy it code. ;)

**Comment by drcxd** [comment]
Sorry I didn't get your idea. Will you rename these branches? Or you were suggesting something else?
The full list of repositories with the branch name issues are here:
+ find-orphan
+ grammatical-edit
+ isearch-mb
+ one-key
+ popweb
+ sort-tab
+ toggle-one-window

**Comment by manateelazycat** [comment]
I mean you can use ```git checkout master``` or ```git checkout main```, not every submodule is mine, such as isearch-mb, I can't rename branch repo that is not create by me.

**Comment by drcxd** [comment]
Okay, since the `git checkout *` command is executed inside the scope of `git submodule foreach`, I have to use either `master` or `main` for all the submodules, and this will not work for all the submodules, which is the reason why I opened this issue. Basically, I do not know an elegant way to prepare all the submodules. I know little about git, if you know anything like `git submodule foreach` in README which would help me to checkout all these submodules with one command, could you tell me how can I do that? Or do I have to check out these submodules one by one manually with the correct branch name?

**Comment by manateelazycat** [comment]
No, I have no idea, sorry I can't help you.
