### ISSUE TITLE
问题？

### ISSUE THREAD

**Issue by PandaZhym** [manateelazycat/lazycat-emacs#36]
当我在lazycat-emacs文件夹运行 git submodule foreach git checkout master
出现下面错误：
您的分支与上游分支 'origin/master' 一致。
进入 'site-lisp/extensions/f'
已经位于 'master'
您的分支与上游分支 'origin/master' 一致。
进入 'site-lisp/extensions/find-orphan'
error: 路径规格 'master' 未匹配任何 git 已知文件
fatal: 对 site-lisp/extensions/find-orphan 执行 run_command 返回非零值。
.

**Comment by manateelazycat** [comment]
master分支有问题的时候尝试用 checkout main ， 有些插件因为 github 的原因，不一定是 master 分支。
