### ISSUE TITLE
如何应在ubuntu下配置

### ISSUE THREAD

**Issue by PandaZhym** [manateelazycat/lazycat-emacs#37]
我按照install on arch liunx的五个步骤操作，其中
第一部我使用的是snap安装的；
第二部我安装的方式：sudo apt install ttf-wqy-microhei
之后的三步都有照做。

但是似乎并没有自动配置到新安装的emacs中；
然而，当我打开site-start.el文件，运行M-x eval-buffer是有作用的！

我希望打开emacs的使用应该是自动配置的

麻烦了

**Comment by manateelazycat** [comment]
这是我个人的配置，不对外提供技术支持，主要是分享出来让大家抄配置的，不是分享出来给大家直接用的。
