### ISSUE TITLE
`git checout master` error

### ISSUE THREAD

**Issue by tianheg** [manateelazycat/lazycat-emacs#39]
when running:

```bash
git submodule foreach git checkout master
```

error:

```bash
Entering 'site-lisp/extensions/find-orphan'
error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for site-lisp/extensions/find-orphan
```
why this error:

[find-orphan](https://github.com/manateelazycat/find-orphan)'s default  branch is `main` not `master`

**Comment by manateelazycat** [comment]
It's my personal git project, not design for other people use, thanks for report. ;)

**Comment by vipzrx** [comment]
按照你的emacs.d的readme.md 执行到 
git submodule foreach git checkout master

报错

```
Your branch is up to date with 'origin/master'.
Entering 'site-lisp/extensions/find-orphan'
error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for site-lisp/extensions/find-orphan


```

从这里
https://github.com/manateelazycat/lazycat-emacs/blob/master/.gitmodules
找到如下

```
[submodule "site-lisp/extensions/find-orphan"]
path = site-lisp/extensions/find-orphan
url = https://github.com/manateelazycat/find-orphan
```

发现

https://github.com/manateelazycat/find-orphan
里面是main分支 不是master

不会git 我向用你的emacs.d配置 改怎么修改呢?
