### ISSUE TITLE
Bugs ( maybe ) in site-lisp/extensions/lazycat/basic-toolkit.el

### ISSUE THREAD

**Issue by lshouzhong** [manateelazycat/lazycat-emacs#40]
## How to reproduce

1. open a buffer and add some lines to it
2. call `insert-line-number+`
3. call `strip-line-number`

## What It should be

All line numbers added to the beginning of every line should be removed.

## What I get

Only the line number of the last line was removed. And then I got an error in \*message\*:

```plaintext
Match data clobbered by buffer modification hooks
```

## My question

I found someone had similar problem https://stackoverflow.com/questions/41402028/re-replace-region-match-data-clobbered-by-buffer-modification-hooks

But I had no idea to fix it.

## Besides

In line 133, the rg expression should be `"^[0-9]+ "` ( add one more spaces at the end of the expression). Otherwise, a spaces at the beginning of the line was left after line number was removed.

**Comment by manateelazycat** [comment]
lazycat-emacs just personal config repo, not public plugin, I won't response issue from github.

Sorry.
